# Generated by Django 5.0.6 on 2024-06-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('truck', 'Truck')], max_length=10)),
                ('slot_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('truck', 'Truck')], max_length=10)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lot_id', models.CharField(max_length=10, unique=True)),
                ('floors', models.ManyToManyField(to='parking_lot_api.floor')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='slots',
            field=models.ManyToManyField(to='parking_lot_api.parkingslot'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=15, unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot_api.floor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot_api.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot_api.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_lot_api.vehicles'),
        ),
    ]
